// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqbtzmolhvhzpfitkcsb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxYnR6bW9saHZoenBmaXRrY3NiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NjE3MzIsImV4cCI6MjA2MzIzNzczMn0.Gg4Ou6eIFzieJP4BUi9f2bL8ZoNrT8KkIFWGuleEpm0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);